/**
 * Registrable domains that share one sign-in, so a login saved for one is offered on the
 * others: Google's accounts serve YouTube, a bank's brand domain and its banking domain, a
 * shop's country storefronts. Conservative on purpose: every group is one owner's set of
 * sites behind one account. A group never bridges to a site that merely embeds another.
 */
const GROUPS: readonly (readonly string[])[] = [
  [
    "google.com",
    "youtube.com",
    "gmail.com",
    "googlemail.com",
    "google.co.uk",
    "google.de",
    "google.fr",
    "google.co.in",
    "google.ca",
    "google.com.au",
    "google.co.jp",
  ],
  ["apple.com", "icloud.com"],
  [
    "microsoft.com",
    "live.com",
    "outlook.com",
    "hotmail.com",
    "office.com",
    "microsoftonline.com",
    "xbox.com",
    "skype.com",
    "msn.com",
    "azure.com",
    "onedrive.com",
    "sharepoint.com",
    "microsoft365.com",
  ],
  [
    "amazon.com",
    "amazon.co.uk",
    "amazon.de",
    "amazon.fr",
    "amazon.it",
    "amazon.es",
    "amazon.ca",
    "amazon.com.au",
    "amazon.co.jp",
    "amazon.in",
    "amazon.com.mx",
    "amazon.nl",
    "amazon.com.br",
    "audible.com",
    "primevideo.com",
  ],
  ["facebook.com", "messenger.com", "fb.com", "facebook.net"],
  ["instagram.com", "threads.net"],
  ["twitter.com", "x.com"],
  ["ebay.com", "ebay.co.uk", "ebay.de", "ebay.fr", "ebay.it", "ebay.es", "ebay.ca", "ebay.com.au"],
  ["paypal.com", "paypal.me"],
  ["steampowered.com", "steamcommunity.com", "steamgames.com"],
  ["discord.com", "discordapp.com", "discord.gg"],
  ["zoom.us", "zoom.com"],
  ["atlassian.com", "atlassian.net", "bitbucket.org", "trello.com", "jira.com"],
  ["notion.so", "notion.com"],
  ["wordpress.com", "wordpress.org"],
  ["mozilla.org", "firefox.com", "mozilla.com"],
  ["proton.me", "protonmail.com", "protonvpn.com"],
  ["intuit.com", "turbotax.com", "quickbooks.com", "mint.com", "creditkarma.com"],
  ["disney.com", "disneyplus.com", "go.com", "hulu.com", "espn.com"],
  ["max.com", "hbomax.com"],
  ["paramountplus.com", "paramount.com", "cbs.com"],
  ["peacocktv.com", "nbc.com", "nbcuniversal.com"],
  ["uber.com", "ubereats.com"],
  ["aa.com", "americanairlines.com"],
  ["wellsfargo.com", "wf.com"],
  ["bankofamerica.com", "bofa.com", "merrilledge.com"],
  ["chase.com", "jpmorgan.com", "jpmorganchase.com"],
  ["americanexpress.com", "amex.com", "aexp.com"],
  ["citi.com", "citibank.com", "citicards.com"],
  ["capitalone.com", "capitalone360.com"],
  ["att.com", "att.net"],
  ["verizon.com", "vzw.com", "verizonwireless.com"],
  ["t-mobile.com", "tmobile.com"],
  ["comcast.com", "xfinity.com", "comcast.net"],
  ["squareup.com", "cash.app", "block.xyz"],
  ["sony.com", "playstation.com", "sonyentertainmentnetwork.com"],
  ["ea.com", "origin.com"],
  ["epicgames.com", "unrealengine.com", "fortnite.com"],
  ["ubisoft.com", "ubi.com"],
  ["blizzard.com", "battle.net"],
  ["nintendo.com", "nintendo.net"],
  ["salesforce.com", "force.com", "salesforce-sites.com"],
  ["vmware.com", "broadcom.com"],
  ["dropbox.com", "dropboxusercontent.com"],
  ["yahoo.com", "aol.com", "yahoo.co.uk", "yahoo.co.jp"],
  ["okta.com", "oktapreview.com", "okta-emea.com"],
  ["1password.com", "1password.eu", "1password.ca"],
  ["bitwarden.com", "bitwarden.eu"],
  ["fidelity.com", "netbenefits.com"],
  ["schwab.com", "schwabplan.com", "tdameritrade.com"],
  ["vanguard.com", "vanguardinvestor.com"],
  ["marriott.com", "spg.com", "ritzcarlton.com"],
  ["hilton.com", "hiltonhonors.com"],
  ["walmart.com", "samsclub.com", "walmart.ca"],
  ["target.com", "target.ca"],
  ["costco.com", "costco.ca"],
  ["homedepot.com", "homedepot.ca"],
  ["lowes.com", "lowes.ca"],
  ["expedia.com", "hotels.com", "vrbo.com", "orbitz.com", "travelocity.com"],
  ["booking.com", "priceline.com", "agoda.com", "kayak.com"],
  ["shopify.com", "myshopify.com"],
  ["godaddy.com", "secureserver.net"],
  ["cloudflare.com", "cloudflareaccess.com"],
  ["digitalocean.com", "digitaloceanspaces.com"],
  ["heroku.com", "herokuapp.com"],
  ["stackoverflow.com", "stackexchange.com", "superuser.com", "serverfault.com", "askubuntu.com"],
  ["reddit.com", "redd.it"],
  ["twitch.tv", "twitchcdn.net"],
  ["tiktok.com", "tiktokv.com"],
  ["linkedin.com", "lnkd.in"],
];

const groupByDomain = new Map<string, ReadonlySet<string>>();
for (const group of GROUPS) {
  const set: ReadonlySet<string> = new Set(group);
  for (const domain of group) groupByDomain.set(domain, set);
}

/** The registrable domains that share `domain`'s sign-in, `domain` included; none when unknown. */
export function equivalentDomainsOf(domain: string): ReadonlySet<string> | undefined {
  return groupByDomain.get(domain);
}
